language: c
compiler: gcc
os: linux
addons:
  apt:
    packages:
    - make
    - autoconf
    - automake
    - m4
    - perl
    - libtool
    - pkg-config
    - gawk
script:
  - perl set.pl 'debian'
  - autoreconf -if
  - make
branches:
  only:
    - master
sudo: false
